### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by mmenbawy** [shakti-garg/opentracing-python-kafka-client#1]
Can the README.md be enhanced with examples of how to use this package with Kafka a python Kafka client.

**Comment by mmenbawy** [comment]
@shakti-garg

**Comment by shakti-garg** [comment]
@mmenbawy Sorry for very very very late response. I have enhanced the README with usage examples and other operational and academic details.

I am not sure if it is still relevant for you but thanks for raising this issue. I created it for personal usage and didn't give it much thought for other's usage.

Please share if you have any further feedbacks!! :)
